CREATE DATABASE DB_GENERATION_GAME_ONLINE;
USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES(
ID BIGINT(5) AUTO_INCREMENT,
CLASSE VARCHAR(255),
DEFESA BIGINT(255), 
ATAQUE BIGINT(255), 
PRIMARY KEY (ID)
);
SELECT * FROM TB_CLASSES;
ALTER TABLE TB_CLASSES MODIFY ATAQUE BIGINT(255);
ALTER TABLE TB_CLASSES MODIFY DEFESA BIGINT(255);


CREATE TABLE TB_PERSONAGEM(
ID BIGINT(5) AUTO_INCREMENT,
NICKNAME VARCHAR(255) NOT NULL,
CLASSES_CLASSE BIGINT(5),
NOME VARCHAR(255),
EMAIL VARCHAR(255),
IDADE INT(2),
PRIMARY KEY (ID),
FOREIGN KEY (CLASSES_CLASSE) REFERENCES TB_CLASSES(ID)
);
SELECT * FROM TB_PERSONAGEM;


INSERT INTO TB_CLASSES (CLASSE,DEFESA,ATAQUE) VALUES ("ARQUEIROS",1500,2000);
INSERT INTO TB_CLASSES (CLASSE,DEFESA,ATAQUE) VALUES ("SOLDADOS",2500,1500);
INSERT INTO TB_CLASSES (CLASSE,DEFESA,ATAQUE) VALUES ("FUZILEIROS",900,3000);
INSERT INTO TB_CLASSES (CLASSE,DEFESA,ATAQUE) VALUES ("ZOMBIES",1000,1000);
INSERT INTO TB_CLASSES (CLASSE,DEFESA,ATAQUE) VALUES ("MEDICO",200,0);

INSERT INTO TB_PERSONAGEM (NICKNAME,CLASSES_CLASSE,NOME,EMAIL,IDADE) VALUES ("JUBILEUBS",1,"JULIA","JULIAGALIBARROSO@GMAIL.COM",18);
INSERT INTO TB_PERSONAGEM (NICKNAME,CLASSES_CLASSE,NOME,EMAIL,IDADE) VALUES ("3.14NOTTI",3,"NICOLAS","PINOTTI@GMAIL.COM",18);
INSERT INTO TB_PERSONAGEM (NICKNAME,CLASSES_CLASSE,NOME,EMAIL,IDADE) VALUES ("ELLENZITCHA",3,"ELLEN","ELLENBUENO@GMAIL.COM",18);
INSERT INTO TB_PERSONAGEM (NICKNAME,CLASSES_CLASSE,NOME,EMAIL,IDADE) VALUES ("BARBOSA_GB",2,"GABRIEL","GABRIELBARBOSA@GMAIL.COM",20);
INSERT INTO TB_PERSONAGEM (NICKNAME,CLASSES_CLASSE,NOME,EMAIL,IDADE) VALUES ("LET_LINDA",2,"LETICIA","LETICIAFATEC@GMAIL.COM",19);
INSERT INTO TB_PERSONAGEM (NICKNAME,CLASSES_CLASSE,NOME,EMAIL,IDADE) VALUES ("ALLONSO_",5,"CAROL","CAROLALONSOO@GMAIL.COM",20);
INSERT INTO TB_PERSONAGEM (NICKNAME,CLASSES_CLASSE,NOME,EMAIL,IDADE) VALUES ("FIRIDA",4,"CAROLINA","CAROLINA@GMAIL.COM",22);
INSERT INTO TB_PERSONAGEM (NICKNAME,CLASSES_CLASSE,NOME,EMAIL,IDADE) VALUES ("LUZIA01",4,"LUZIA","LUZIAABRAO@GMAIL.COM",26);

SELECT * FROM TB_PERSONAGEM INNER JOIN TB_CLASSES ON TB_PERSONAGEM.CLASSES_CLASSE = TB_CLASSES.ID;

SELECT * FROM TB_PERSONAGEM INNER JOIN TB_CLASSES ON TB_PERSONAGEM.CLASSES_CLASSE = TB_CLASSES.ID WHERE ATAQUE > 2000;
SELECT * FROM TB_PERSONAGEM INNER JOIN TB_CLASSES ON TB_PERSONAGEM.CLASSES_CLASSE = TB_CLASSES.ID WHERE DEFESA BETWEEN 1000 AND 2000;
SELECT * FROM TB_PERSONAGEM INNER JOIN TB_CLASSES ON TB_PERSONAGEM.CLASSES_CLASSE = TB_CLASSES.ID WHERE NOME LIKE "C%";
SELECT * FROM TB_PERSONAGEM INNER JOIN TB_CLASSES ON TB_PERSONAGEM.CLASSES_CLASSE = TB_CLASSES.ID WHERE CLASSES_CLASSE = 1;


