CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT(5) AUTO_INCREMENT,
TIPO INT(1),
PRECO DECIMAL(6,2),
PRIMARY KEY (ID)
);
SELECT * FROM TB_CATEGORIAS;

CREATE TABLE TB_PIZZAS(
ID BIGINT(5) AUTO_INCREMENT,
SABOR VARCHAR(255),
INGREDIENTES VARCHAR(255),
BORDA VARCHAR(255),
TIPO_PIZZA BIGINT(5),
PRIMARY KEY(ID),
FOREIGN KEY(TIPO_PIZZA) REFERENCES TB_CATEGORIAS(ID)
);
SELECT * FROM TB_PIZZAS;

INSERT INTO TB_CATEGORIAS (TIPO,PRECO) VALUES ("SALGADA", 75);
INSERT INTO TB_CATEGORIAS (TIPO,PRECO) VALUES ("SALGADA PREMIUM", 85);
INSERT INTO TB_CATEGORIAS (TIPO,PRECO) VALUES ("DOCE", 85);
INSERT INTO TB_CATEGORIAS (TIPO,PRECO) VALUES ("DOCE PREMIUM", 105);
INSERT INTO TB_CATEGORIAS (TIPO,PRECO) VALUES ("COMBO DOCE E SALGADA PREMIUM", 140);
INSERT INTO TB_CATEGORIAS (TIPO,PRECO) VALUES ("COMBO DOCE E SALGADA", 129.90);

INSERT INTO TB_PIZZAS (SABOR,INGREDIENTES,BORDA,TIPO_PIZZA) VALUES ("ATUM","ATUM, CEBOLA E MUSSARELA","SEM RECHEIO",1);
INSERT INTO TB_PIZZAS (SABOR,INGREDIENTES,BORDA,TIPO_PIZZA) VALUES ("MARGERITTA","TOMATE, OREGANO E MUSSARELA","CATUPIRY",1);
INSERT INTO TB_PIZZAS (SABOR,INGREDIENTES,BORDA,TIPO_PIZZA) VALUES ("CALABRESA","CALABRESA, CEBOLA E MUSSARELA","CHEDDAR",2);
INSERT INTO TB_PIZZAS (SABOR,INGREDIENTES,BORDA,TIPO_PIZZA) VALUES ("PEPPER BROCOLIS","FATIAS DE PEPPERONI, BROCOLIS E CATUPIRY","CHEDDAR",2);
INSERT INTO TB_PIZZAS (SABOR,INGREDIENTES,BORDA,TIPO_PIZZA) VALUES ("BRIGADEIRO","CHOCOLATE E GRANULADO","GOIABA",3);
INSERT INTO TB_PIZZAS (SABOR,INGREDIENTES,BORDA,TIPO_PIZZA) VALUES ("OREO","CHOCOLATE E RASPAS DE OREO","CHOCOLATE",4);
INSERT INTO TB_PIZZAS (SABOR,INGREDIENTES,BORDA,TIPO_PIZZA) VALUES ("FRANGO COM CATUPIRY E BRIGADEIRO","VARIADOS","CHEDDAR E GOIABA",6);
INSERT INTO TB_PIZZAS (SABOR,INGREDIENTES,BORDA,TIPO_PIZZA) VALUES ("PEPERONI COM CHEDAR E NINHO","VARIADOS","CHEDDAR E CHOCOLATE",5);


SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.TIPO_PIZZA = TB_CATEGORIAS.ID WHERE PRECO > 45;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.TIPO_PIZZA = TB_CATEGORIAS.ID WHERE PRECO BETWEEN 50 AND 100;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.TIPO_PIZZA = TB_CATEGORIAS.ID WHERE SABOR LIKE "P%";
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.TIPO_PIZZA = TB_CATEGORIAS.ID WHERE TIPO_PIZZA = 1;



