CREATE DATABASE DB_FARMACIA_BEM_ESTAR;
USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT(5) AUTO_INCREMENT,
CATEGORIA VARCHAR(255),
RESTRICAO VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
PRECO DECIMAL(6,2),
QUANTIDADE INT(5),
PESO DECIMAL(6,2),
MARCA VARCHAR(255),
CATEGORIA_PRODUTO BIGINT(5),
PRIMARY KEY(ID),
FOREIGN KEY (CATEGORIA_PRODUTO) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS (CATEGORIA,RESTRICAO) VALUES ("BELEZA E ESTETICA","NAO INGERIR");
INSERT INTO TB_CATEGORIAS (CATEGORIA,RESTRICAO) VALUES ("MEDICAMENTOS","RESTRICOES NA BULA");
INSERT INTO TB_CATEGORIAS (CATEGORIA,RESTRICAO) VALUES ("INFANTIL","NAO ENTRAR EM CONTATO COM OS OLHOS");
INSERT INTO TB_CATEGORIAS (CATEGORIA,RESTRICAO) VALUES ("HIGIENE","NAO INGERIR");
INSERT INTO TB_CATEGORIAS (CATEGORIA,RESTRICAO) VALUES ("ALIMENTOS","ATENTE-SE AO PRAZO DE VALIDADE");
INSERT INTO TB_CATEGORIAS (CATEGORIA,RESTRICAO) VALUES ("DERMO-COSMETICOS","NAO INGERIR");
INSERT INTO TB_CATEGORIAS (CATEGORIA,RESTRICAO) VALUES ("FITNESS","RESTRICOES NA EMBALAGEM");
INSERT INTO TB_CATEGORIAS (CATEGORIA,RESTRICAO) VALUES ("IDOSO","RESTRICOES NA EMBALAGEM");
SELECT * FROM TB_CATEGORIAS;


INSERT INTO TB_PRODUTOS (NOME,PRECO,QUANTIDADE,PESO,MARCA,CATEGORIA_PRODUTO) VALUES ("SHAMPOO SEM LAGRIMAS BABY",22,1,0.50,"JHONSSONS&JHONSSONS",3);
INSERT INTO TB_PRODUTOS (NOME,PRECO,QUANTIDADE,PESO,MARCA,CATEGORIA_PRODUTO) VALUES ("DANONE LESS IT'S MORE",7.50,3,0.20,"ACTIVIA",7);
INSERT INTO TB_PRODUTOS (NOME,PRECO,QUANTIDADE,PESO,MARCA,CATEGORIA_PRODUTO) VALUES ("BATOM HIDRATANTE GLOW",5,1,0.10,"AVON",1);
INSERT INTO TB_PRODUTOS (NOME,PRECO,QUANTIDADE,PESO,MARCA,CATEGORIA_PRODUTO) VALUES ("HIDRATANTE CORPORAL",22,1,0.50,"OBOTICARIO",6);
INSERT INTO TB_PRODUTOS (NOME,PRECO,QUANTIDADE,PESO,MARCA,CATEGORIA_PRODUTO) VALUES ("BASE MATTE PARA ROSTO",65,1,0.40,"MAYBELINE",1);
INSERT INTO TB_PRODUTOS (NOME,PRECO,QUANTIDADE,PESO,MARCA,CATEGORIA_PRODUTO) VALUES ("ESFOLIANTE CORPORAL",50.90,1,0.50,"GRAMADO",6);
INSERT INTO TB_PRODUTOS (NOME,PRECO,QUANTIDADE,PESO,MARCA,CATEGORIA_PRODUTO) VALUES ("PROTETOR SOLAR 80",75,2,0.50,"GARNIER LOREAL",6);
INSERT INTO TB_PRODUTOS (NOME,PRECO,QUANTIDADE,PESO,MARCA,CATEGORIA_PRODUTO) VALUES ("CIROXCICAM",35,7,0.10,"GENERICO",2);
SELECT * FROM TB_PRODUTOS;


SELECT * FROM TB_PRODUTOS WHERE PRECO > 50;
SELECT * FROM TB_PRODUTOS WHERE PRECO BETWEEN 5 AND 60;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIA_PRODUTO = TB_CATEGORIAS.ID WHERE CATEGORIA_PRODUTO = 6;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIA_PRODUTO = TB_CATEGORIAS.ID;
