CREATE DATABASE ECOMMERCE;

USE ECOMMERCE;

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
DESCRICAO VARCHAR(1000),
VALOR BIGINT,
LOTE INT,
VALIDADE CHAR(255),
QUANTIDADE INT,
PRIMARY KEY (ID)

);

INSERT INTO TB_PRODUTOS (DESCRICAO,VALOR,LOTE,VALIDADE,QUANTIDADE) 
VALUES ("PRINGLES",13,7,"DEZEMBRO",3);
INSERT INTO TB_PRODUTOS (DESCRICAO,VALOR,LOTE,VALIDADE,QUANTIDADE) 
VALUES ("DORITOS",11,5,"JANEIRO",1);
INSERT INTO TB_PRODUTOS (DESCRICAO,VALOR,LOTE,VALIDADE,QUANTIDADE) 
VALUES ("CEBOLITOS",12,7,"OUTUBRO",2);
INSERT INTO TB_PRODUTOS (DESCRICAO,VALOR,LOTE,VALIDADE,QUANTIDADE) 
VALUES ("PIPOCA",7,9,"FEVEREIRO",1);
INSERT INTO TB_PRODUTOS (DESCRICAO,VALOR,LOTE,VALIDADE,QUANTIDADE) 
VALUES ("MIOJO TALHARIM",20,7,"FEVEREIRO",4);
INSERT INTO TB_PRODUTOS (DESCRICAO,VALOR,LOTE,VALIDADE,QUANTIDADE) 
VALUES ("BATATA FRITA 1KG",30,4,"DEZEMBRO",1);
INSERT INTO TB_PRODUTOS (DESCRICAO,VALOR,LOTE,VALIDADE,QUANTIDADE) 
VALUES ("LASANHA MICROONDAS",25,7,"FEVEREIRO",1);
INSERT INTO TB_PRODUTOS (DESCRICAO,VALOR,LOTE,VALIDADE,QUANTIDADE) 
VALUES ("MOLHO DE TOMATE",13,8,"FEVEREIRO",5);
INSERT INTO TB_PRODUTOS (DESCRICAO,VALOR,LOTE,VALIDADE,QUANTIDADE) 
VALUES ("DANONE",7,3,"NOVEMBRO",3);

SELECT * FROM TB_PRODUTOS WHERE VALOR < 500;
SELECT * FROM TB_PRODUTOS WHERE VALOR > 500;
UPDATE TB_PRODUTOS SET LOTE = 10 WHERE ID = 3;

SELECT * FROM TB_PRODUTOS;