CREATE DATABASE DB_ESCOLA;

USE DB_ESCOLA;

CREATE TABLE TB_ESTUDANTE(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
NOTA1 DECIMAL(10),
NOTA2 DECIMAL(10),
NOTA3 DECIMAL(10),
MEDIA DECIMAL(10),
PRIMARY KEY (ID)
);


INSERT INTO TB_ESTUDANTE (NOME,NOTA1,NOTA2,NOTA3,MEDIA) VALUES ("NÍCOLAS",10,10,10,10);
INSERT INTO TB_ESTUDANTE (NOME,NOTA1,NOTA2,NOTA3,MEDIA) VALUES ("JULIA",5,5,10,6);
INSERT INTO TB_ESTUDANTE (NOME,NOTA1,NOTA2,NOTA3,MEDIA) VALUES ("JOAO",5,0,0,1);
INSERT INTO TB_ESTUDANTE (NOME,NOTA1,NOTA2,NOTA3,MEDIA) VALUES ("PEDRO RICARDO",5,5,10,6);
INSERT INTO TB_ESTUDANTE (NOME,NOTA1,NOTA2,NOTA3,MEDIA) VALUES ("THAYNA",10,10,10,10);
INSERT INTO TB_ESTUDANTE (NOME,NOTA1,NOTA2,NOTA3,MEDIA) VALUES ("THAIS",5,7,10,7);
INSERT INTO TB_ESTUDANTE (NOME,NOTA1,NOTA2,NOTA3,MEDIA) VALUES ("JOAO VITOR",0,0,0,0);


SELECT * FROM TB_ESTUDANTE WHERE MEDIA < 7;
SELECT * FROM TB_ESTUDANTE WHERE MEDIA > 7;
UPDATE TB_ESTUDANTE SET MEDIA = 6 WHERE ID = 4;
UPDATE TB_ESTUDANTE SET NOME = "LUCAS" WHERE ID = 3;
UPDATE TB_ESTUDANTE SET NOME = "JULIA SILVA" WHERE ID = 2;

SELECT * FROM TB_ESTUDANTE;