CREATE DATABASE DB_SERVICO_RH;

USE DB_SERVICO_RH;

CREATE TABLE TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
IDADE INT, 
FUNCAO CHAR(255),
SALARIO BIGINT,
TELEFONE BIGINT,
PRIMARY KEY (ID)

);

INSERT INTO TB_FUNCIONARIOS (NOME,IDADE,FUNCAO,SALARIO,TELEFONE) 
VALUES ("BEATRIZ SANTOS",27,"SCRUM MASTER",3800,97841245);

/* Ações executadas para realizar a atividade:*/
ALTER TABLE TB_FUNCIONARIOS ADD SALARIO BIGINT;
ALTER TABLE TB_FUNCIONARIOS ADD TELEFONE BIGINT; 
SET SQL_SAFE_UPDATES = 0;
DELETE FROM TB_FUNCIONARIOS WHERE ID=13;
SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO<2000;
SELECT * FROM TB_FUNCIONARIOS WHERE SALARI<<2000;
UPDATE TB_FUNCIONARIOS SET SALARIO = 1000 WHERE ID = 16;
DELETE FROM TB_FUNCIONARIOS WHERE ID = 17;

SELECT * FROM TB_FUNCIONARIOS;